### ISSUE TITLE
crashes if using geopandas GeoDataFrame instead of pandas

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/disarm-gears#10]
https://github.com/disarm-platform/disarm-gears/blob/653fbce7e437d27975f262ed65c21b57339c4770/disarm_gears/r_plugins/r_methods.py#L25

Was trying to pass a GeoDataFrame from https://github.com/disarm-platform/fn-prevalence-predictor.

GeoPandas makes sense for handling incoming GeoJSON to a function, but seems not supported by `rpy2`.

**Comment by ric70x7** [comment]
Probably this is not really an issue for this particular set of functions. It may be a disadvantage to force all functions in disarm-gears to get geopandas dataframes as inputs. The functions in disarm-gears are meant to be called within the different handler.py scripts for modeling some data features only. I don't see disarm-gears as entry/exit point to the functions in open-faas. As long as in the handler we work with a geopandas (still not sure why we want that in every case) we shouldn't have a problem.

**Comment by onlyjsmith** [comment]
Agree - think is related to discussion on https://github.com/disarm-platform/fn-prevalence-predictor/issues/13. Can reopen a new issue if we need
