### ISSUE TITLE
is this repo a pip package?

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/disarm-gears#5]
@ric70x7 have you had success install from this repo outside the fn-prev function? I just tried locally and I get the same error as during the container build.

I checked the repo we created the gears PyPI package from, and it looks different: https://github.com/disarm-dev/disarm-gears/tree/develop (note it's on the `develop` branch).

**Comment by onlyjsmith** [comment]
Btw, I think this link explains what's needed: https://packaging.python.org/tutorials/packaging-projects/

I just saw another couple resources which talk about 'packages' and look much simpler (i.e. just needing an `__init__.py` file), but it seems they might just be local, and are different to installable _PyPI packages_.

Can't remember exactly the tool I used with the original disarm-gears pip package, but it might have been [Cookiecutter](https://cookiecutter.readthedocs.io/en/latest/). There are some instructions in a useful overview [here](https://realpython.com/pypi-publish-python-package/#cookiecutter)

**Comment by ric70x7** [comment]
@onlyjsmith:
 - It is not a pip package. I don't know how to update the version in pip, but I think we should be able to install it from git, that's the way I did it in Algorithmia some time back.
 - I haven't tried installing it outside fn-prev-function.
 -Yes it is the master branch and it is different. I removed things that are not currently used from develop, corrected a few other, and included some tests. 
 - It currently has __init__ files needed to run locally. I don't think that is the problem.

**Comment by ric70x7** [comment]
I see the problem! I didn't add the manifest, requirements, setup, etc. I'll do that tomorrow.

**Comment by ric70x7** [comment]
Indeed that was the issue. The file MANIFEST.in is not needed, but this are the ones I added:
 - requirements.txt
 - setup.py
 - README
 - LICENCE

**Comment by onlyjsmith** [comment]
Great!

Btw, I tagged the current master with the version from `setup.py`.

If you update the code, I'd suggest doing it again: make it much easier to reference multiple versions in different repos. 

It's very quick: once you've pushed some new code to `master` branch, just visit the 'Releases' tab - [here](https://github.com/disarm-platform/disarm-gears/releases/new) for this repo. Then you just enter the version (usually prefixed with a `v`, like `v0.1.2`), and click publish - everything else is optional.

![image](https://user-images.githubusercontent.com/148280/53936855-f8436200-40b3-11e9-8bce-17750ac60ac8.png)
