### ISSUE TITLE
return GeoJSON

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/disarm-gears#6]
Specifically from the `adaptive_prototype_0` method, but might be relevant elsewhere too.

https://github.com/disarm-platform/disarm-gears/blob/fcad34cac48f1f6822097d50a2feccc4acf96fca/disarm_gears/chain_drives/prototypes/prototype_adaptive.py#L119

**Comment by ric70x7** [comment]
This functionality is now handled in a disarm-platform/fn-adaptive-sampling
